name: 01. Comby replace prints

on:
  workflow_dispatch:

jobs:
  comby-refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace print(...) with logger.info(...)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/work -w /work \
            --user "$(id -u):$(id -g)" \
            comby/comby:latest \
            -matcher .py 'print(:[msg])' 'logger.info(:[msg])' -in-place '.py'

      - name: Summarize changes (Git diff)
        run: |
          echo "## 01. Comby refactor summary" >> $GITHUB_STEP_SUMMARY

          changed=$(git status --porcelain | wc -l)
          if [ "$changed" -eq 0 ]; then
            echo "No se detectaron cambios." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Modifications" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          git status --porcelain | awk '{print $2}' | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Statistics" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "`$(git diff --shortstat)`" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Show diff</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
