name: 03. ast-grep replace prints to powertools logger

on:
  workflow_dispatch:

env:
  AST_GREP_VERSION: 0.39.3

jobs:
  ast-grep-refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ast-grep CLI
        run: |
          pip install ast-grep-cli==$AST_GREP_VERSION
          ast-grep --version

      - name: Replace print(...) with logger with YAML rules mode
        run: |
          ast-grep scan \
          -r ast-grep-rules/replace_print_to_powertools_logger.yml \
          --report-style=rich  . --update-all

      - name: Summarize changes (Git diff)
        run: |
          echo "## ast-grep refactor summary" >> $GITHUB_STEP_SUMMARY
          if git diff --quiet; then
            echo "No se detectaron cambios." >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Modifications" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          git status --porcelain | awk '{print $2}' | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Statistics" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "`$(git diff --shortstat)`" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Show diff</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
