name: 04. grit refactor

on:
  workflow_dispatch:

env:
  GRIT_VERSION: "0.1.0-alpha.1743007075"
  TERM: xterm-256color
  CLICOLOR: "1"
  FORCE_COLOR: "1"

jobs:
  grit-refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git (local commits for diffs)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f grit_before

      - name: Install grit CLI
        run: |
          npm install --location=global @getgrit/cli@$GRIT_VERSION
          grit --version

      - name: List available rules
        run: grit list

      - name: Run rules in dry-run mode
        run: |
          grit apply append_powertools_import_after_last_import . --dry-run
          grit apply replace_print_with_logger_info . --dry-run
          grit apply lambda_handler_insert_event . --dry-run

      - name: Apply rule 1 and commit if changed
        env:
          RULE_ID: append_powertools_import_after_last_import
        run: |
          grit apply "$RULE_ID" . --force
          if ! git diff --quiet; then
            git add -A
            git commit -m "[grit] $RULE_ID"
            echo "RULE1_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Apply rule 2 and commit if changed
        env:
          RULE_ID: replace_print_with_logger_info
        run: |
          grit apply "$RULE_ID" . --force
          if ! git diff --quiet; then
            git add -A
            git commit -m "[grit] $RULE_ID"
            echo "RULE2_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Apply rule 3 and commit if changed
        env:
          RULE_ID: lambda_handler_insert_event
        run: |
          grit apply "$RULE_ID" . --force
          if ! git diff --quiet; then
            git add -A
            git commit -m "[grit] $RULE_ID"
            echo "RULE3_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Summarize changes (baseline vs total and per rule)
        shell: bash
        run: |
          {
            echo "## grit refactor summary"
            echo

            # Si no hay cambios respecto al baseline:
            if git diff --quiet grit_before..HEAD; then
              echo "No se detectaron cambios."
              exit 0
            fi

            echo "### Archivos modificados (global)"
            echo
            git diff --name-status grit_before..HEAD | sed 's/^/- /'
            echo

            echo "### Estadísticas (global)"
            echo
            echo "\`$(git diff --shortstat grit_before..HEAD)\`"
            echo

            # Diff por regla (si existió commit para la regla)
            prev_ref="grit_before"
            for i in 1 2 3; do
              sha_var="RULE${i}_SHA"
              sha_val=${!sha_var:-}
              [ -z "$sha_val" ] && continue

              title=$(git log -1 --pretty=%s "$sha_val")
              echo "### ${title}"
              echo
              echo "\`$(git diff --shortstat ${prev_ref}..${sha_val})\`"
              echo
              echo "<details><summary>Mostrar diff</summary>"
              echo
              echo '```diff'
              git --no-pager diff ${prev_ref}..${sha_val}
              echo '```'
              echo "</details>"
              echo

              prev_ref="$sha_val"
            done

            # Diff global expandible
            echo "### Diff global (grit_before..HEAD)"
            echo
            echo "<details><summary>Mostrar diff completo</summary>"
            echo
            echo '```diff'
            git --no-pager diff grit_before..HEAD
            echo '```'
            echo "</details>"
          } >> "$GITHUB_STEP_SUMMARY"
